### ISSUE TITLE
"TypeError: dom.byId(...) is null" after setting gamePage.paragonPoints to 3000.

### ISSUE THREAD

**Issue by Gua** [dwhalen/linearKittens#13]
kittensGame version Ver 1.1.7.6.  linearKittens as of today. When running startKittens(); I get "TypeError: dom.byId(...) is null", and "PLANNING LOOP" is the only thing that shows up.  No list of things it decided to do.

**Comment by dwhalen** [comment]
I just added an update that should have fixed it.  Let me know if it's still broken.

**Comment by Gua** [comment]
Thanks, now that's what I call support. Happy "Cyber Monday"

```
  From: dwhalen <notifications@github.com>
```

 To: dwhalen/linearKittens linearKittens@noreply.github.com 
Cc: Gua dvd_id10t@yahoo.com
 Sent: Monday, November 30, 2015 10:53 AM
 Subject: Re: [linearKittens] "TypeError: dom.byId(...) is null" after setting gamePage.paragonPoints to 3000. (#13)

I just added an update that should have fixed it. Let me know if it's still broken.—
