### ISSUE TITLE
Starclick routine is out of date

### ISSUE THREAD

**Issue by callmemorgan** [dwhalen/linearKittens#17]
```
 function starClickFunction () { $("#gameLog").find("input").click(); }
```

does not work and should now be

```
 function starClickFunction () { $("#observeBtn").click(); }
```

with the log updates. 

Also, `starClick = setInterval(starClickFunction, 1*1000);` could go slower too.

**Comment by dwhalen** [comment]
I've made the suggested changes.  Thanks!
