### ISSUE TITLE
game.village.invalidateCachedEffects is not a function (Version 1.2.1.1)

### ISSUE THREAD

**Issue by callmemorgan** [dwhalen/linearKittens#22]
Currently, the AI does not work because this function appears to be missing from the latest kittensgame.

**Comment by dwhalen** [comment]
This is actually pretty ugly; the recent update broke most of the methods I used to get per-tick rates for resource generation.  I probably won't be able to get to this until this weekend.

**Comment by dwhalen** [comment]
It works for me now, although some of the fixes were hackish, and I haven't done extensive testing.
