### ISSUE TITLE
Trading - Blueprints and Spices

### ISSUE THREAD

**Issue by ratbasher** [dwhalen/linearKittens#24]
Blueprints and spices show up in the log, But in my resources I am not actually getting them.  If I stop Linear kittens and do manual trades I do receive the blueprints and spices when they show in the log.  If I restart Linearkittens my Blueprints will stay the same.  Attached is my save file.
[kittens.txt](https://github.com/dwhalen/linearKittens/files/676082/kittens.txt)

**Comment by HeyItsJono** [comment]
Same issue on my end, save file is attached.
[kittens.txt](https://github.com/dwhalen/linearKittens/files/676536/kittens.txt)

**Comment by dwhalen** [comment]
Should be fixed now.  The problem was that the temporary copy of the game that linearKittens uses to simulate trades was printing messages to the main message window.
