### ISSUE TITLE
Script outdated?

### ISSUE THREAD

**Issue by beastyrabbit** [dwhalen/linearKittens#25]
I tryed to run the script and every time I temporarily remove an Error a new Error occurs.

Is the Script not up-to-date?

**Comment by dwhalen** [comment]
The script is out-of-date. I'll close this issue when the script runs again successfully.

**Comment by dwhalen** [comment]
The script has been updated for the new version of the game. It works in early game, but late game has not been tested. If you encounter problems, can you start a new issue and post your exported save file?
