### ISSUE TITLE
Unicorn sacrifices aren't being considered.

### ISSUE THREAD

**Issue by Destrictor** [dwhalen/linearKittens#28]
Inside the function getTradeRates: on lines 337, 342 and 347 you check for button.visible,
however when I was debugging, visible isn't defined, which makes the game never sacrifice unicorns.
Are these perhaps also supposed to use button.model.visible like in the trade/craft parts of that method?

**Comment by dwhalen** [comment]
I believe you are correct. If you'd like to submit a patch, I'll accept it it. Otherwise, it will be a couple of days before I can fix and test it.

**Comment by ValentinKlamka** [comment]
Another problem is that the Ziggurat upgrades are not researched in an efficient order. A rule of tumb for what to upgrade next would be: expected unicorn bonus devided by number of tears you need for that upgrade. The upgrade with the higher ratio should be researched next, also if that means that you have to wait a bit longer. But the linear program just upgrades the building with the lowest cost first, which is inefficient. 
So If there is no easy solution to this I would prefer if one could sacrifice and build ziggurat upgrades manually.
