### ISSUE TITLE
The script will keep kittens as scientists even when science is maxed out!

### ISSUE THREAD

**Issue by johnadula** [dwhalen/linearKittens#4]
As the title says. The script will keep kittens as scientists, oftentimes all of them, as scientists even when science is maxed out. I think it does it when it desperately wants to buy the next science/workshop improvement, not keeping in mind the requisites for buying them. It's frustrating because it can keep stuck like this for a loooong time without making any progress.

**Comment by dwhalen** [comment]
That's odd.  Do you have an export from a time when this was happening?

**Comment by johnadula** [comment]
Unfortunately not,but it shouldn't be too hard to replicate on a fresh
save, around the time Theology becomes available. The script will keep the
kittens working as scientists with science capped, not minding to assign
them as hunters for the furs >manuscripts >compendiums >blueprints
whatever. Maybe it's a issue with me still having only about 150 paragon.
Em 17/06/2015 21:49, "dwhalen" notifications@github.com escreveu:

**Comment by dwhalen** [comment]
I _think_ that I fixed this with the most recent patch.  If it continues to happen, please let me know.
