### ISSUE TITLE
button.getBuilding is not a functionbuildableWeight - halts the game completely

### ISSUE THREAD

**Issue by mio-moto** [dwhalen/linearKittens#5]
Uncaught TypeError:  button.getBuilding is not a function
buildableWeight @ linearKittens.js:91
linearProgram @ linearKittens.js:790
planLoop @ linearKittens.js:1139

This breaks the execution of the gameloop itself and halts the AI (obviously). This happened in Chrome, but I guess it will be the same around all browsers.

**Comment by dwhalen** [comment]
Should be fixed now!  Thanks for pointing that out.

**Comment by mio-moto** [comment]
That did the trick, works fine again! Thanks for the quick fix.
